services:
  app:
    build: .
    depends_on:
      - pg
    container_name: brevly-backend
    restart: unless-stopped
    ports:
      - 3333:3333
    env_file:
      - .env.docker
    networks:
      - backend
  pg:
    image: bitnami/postgresql
    container_name: brevly-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env.docker
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
    networks:
      - backend
      - database

networks:
  backend:
    driver: bridge
  database:
    driver: bridge
