services:
  app:
    build: .
    depends_on:
      - pg
    container_name: brevly-backend
    restart: unless-stopped
    ports:
      - 3333:3333
    environment:
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
      - FRONTEND_URL=$FRONTEND_URL
      - DATABASE_URL=$DATABASE_URL
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL
    networks:
      - backend

  pg:
    image: bitnami/postgresql
    container_name: brevly-postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
    networks:
      - backend
      - database

networks:
  backend:
    driver: bridge
  database:
    driver: bridge
